#include "ops.h"

op_t ops[OP_COUNT] = 
{
    { "BRK", 7, &op_brk, &am_imm },{ "ORA", 6, &op_ora, &am_x_ind },{ "xxx", 2, &op_xxx, &am_imp },{ "xxx", 8, &op_xxx, &am_imp },{ "xxx", 3, &op_nop, &am_imp },{ "ORA", 3, &op_ora, &am_zpg },{ "ASL", 5, &op_asl, &am_zpg },{ "xxx", 5, &op_xxx, &am_imp },{ "PHP", 3, &op_php, &am_imp },{ "ORA", 2, &op_ora, &am_imm },{ "ASL", 2, &op_asl, &am_imp },{ "xxx", 2, &op_xxx, &am_imp },{ "xxx", 4, &op_nop, &am_imp },{ "ORA", 4, &op_ora, &am_abs },{ "ASL", 6, &op_asl, &am_abs },{ "xxx", 6, &op_xxx, &am_imp },
    { "BPL", 2, &op_bpl, &am_rel },{ "ORA", 5, &op_ora, &am_ind_y },{ "xxx", 2, &op_xxx, &am_imp },{ "xxx", 8, &op_xxx, &am_imp },{ "xxx", 4, &op_nop, &am_imp },{ "ORA", 4, &op_ora, &am_zpg_x },{ "ASL", 6, &op_asl, &am_zpg_x },{ "xxx", 6, &op_xxx, &am_imp },{ "CLC", 2, &op_clc, &am_imp },{ "ORA", 4, &op_ora, &am_abs_y },{ "xxx", 2, &op_nop, &am_imp },{ "xxx", 7, &op_xxx, &am_imp },{ "xxx", 4, &op_nop, &am_imp },{ "ORA", 4, &op_ora, &am_abs_x },{ "ASL", 7, &op_asl, &am_abs_x },{ "xxx", 7, &op_xxx, &am_imp },
    { "JSR", 6, &op_jsr, &am_abs },{ "AND", 6, &op_and, &am_x_ind },{ "xxx", 2, &op_xxx, &am_imp },{ "xxx", 8, &op_xxx, &am_imp },{ "BIT", 3, &op_bit, &am_zpg },{ "AND", 3, &op_and, &am_zpg },{ "ROL", 5, &op_rol, &am_zpg },{ "xxx", 5, &op_xxx, &am_imp },{ "PLP", 4, &op_plp, &am_imp },{ "AND", 2, &op_and, &am_imm },{ "ROL", 2, &op_rol, &am_imp },{ "xxx", 2, &op_xxx, &am_imp },{ "BIT", 4, &op_bit, &am_abs },{ "AND", 4, &op_and, &am_abs },{ "ROL", 6, &op_rol, &am_abs },{ "xxx", 6, &op_xxx, &am_imp },
    { "BMI", 2, &op_bmi, &am_rel },{ "AND", 5, &op_and, &am_ind_y },{ "xxx", 2, &op_xxx, &am_imp },{ "xxx", 8, &op_xxx, &am_imp },{ "xxx", 4, &op_nop, &am_imp },{ "AND", 4, &op_and, &am_zpg_x },{ "ROL", 6, &op_rol, &am_zpg_x },{ "xxx", 6, &op_xxx, &am_imp },{ "SEC", 2, &op_sec, &am_imp },{ "AND", 4, &op_and, &am_abs_y },{ "xxx", 2, &op_nop, &am_imp },{ "xxx", 7, &op_xxx, &am_imp },{ "xxx", 4, &op_nop, &am_imp },{ "AND", 4, &op_and, &am_abs_x },{ "ROL", 7, &op_rol, &am_abs_x },{ "xxx", 7, &op_xxx, &am_imp },
    { "RTI", 6, &op_rti, &am_imp },{ "EOR", 6, &op_eor, &am_x_ind },{ "xxx", 2, &op_xxx, &am_imp },{ "xxx", 8, &op_xxx, &am_imp },{ "xxx", 3, &op_nop, &am_imp },{ "EOR", 3, &op_eor, &am_zpg },{ "LSR", 5, &op_lsr, &am_zpg },{ "xxx", 5, &op_xxx, &am_imp },{ "PHA", 3, &op_pha, &am_imp },{ "EOR", 2, &op_eor, &am_imm },{ "LSR", 2, &op_lsr, &am_imp },{ "xxx", 2, &op_xxx, &am_imp },{ "JMP", 3, &op_jmp, &am_abs },{ "EOR", 4, &op_eor, &am_abs },{ "LSR", 6, &op_lsr, &am_abs },{ "xxx", 6, &op_xxx, &am_imp },
    { "BVC", 2, &op_bvc, &am_rel },{ "EOR", 5, &op_eor, &am_ind_y },{ "xxx", 2, &op_xxx, &am_imp },{ "xxx", 8, &op_xxx, &am_imp },{ "xxx", 4, &op_nop, &am_imp },{ "EOR", 4, &op_eor, &am_zpg_x },{ "LSR", 6, &op_lsr, &am_zpg_x },{ "xxx", 6, &op_xxx, &am_imp },{ "CLI", 2, &op_cli, &am_imp },{ "EOR", 4, &op_eor, &am_abs_y },{ "xxx", 2, &op_nop, &am_imp },{ "xxx", 7, &op_xxx, &am_imp },{ "xxx", 4, &op_nop, &am_imp },{ "EOR", 4, &op_eor, &am_abs_x },{ "LSR", 7, &op_lsr, &am_abs_x },{ "xxx", 7, &op_xxx, &am_imp },
    { "RTS", 6, &op_rts, &am_imp },{ "ADC", 6, &op_adc, &am_x_ind },{ "xxx", 2, &op_xxx, &am_imp },{ "xxx", 8, &op_xxx, &am_imp },{ "xxx", 3, &op_nop, &am_imp },{ "ADC", 3, &op_adc, &am_zpg },{ "ROR", 5, &op_ror, &am_zpg },{ "xxx", 5, &op_xxx, &am_imp },{ "PLA", 4, &op_pla, &am_imp },{ "ADC", 2, &op_adc, &am_imm },{ "ROR", 2, &op_ror, &am_imp },{ "xxx", 2, &op_xxx, &am_imp },{ "JMP", 5, &op_jmp, &am_ind },{ "ADC", 4, &op_adc, &am_abs },{ "ROR", 6, &op_ror, &am_abs },{ "xxx", 6, &op_xxx, &am_imp },
    { "BVS", 2, &op_bvs, &am_rel },{ "ADC", 5, &op_adc, &am_ind_y },{ "xxx", 2, &op_xxx, &am_imp },{ "xxx", 8, &op_xxx, &am_imp },{ "xxx", 4, &op_nop, &am_imp },{ "ADC", 4, &op_adc, &am_zpg_x },{ "ROR", 6, &op_ror, &am_zpg_x },{ "xxx", 6, &op_xxx, &am_imp },{ "SEI", 2, &op_sei, &am_imp },{ "ADC", 4, &op_adc, &am_abs_y },{ "xxx", 2, &op_nop, &am_imp },{ "xxx", 7, &op_xxx, &am_imp },{ "xxx", 4, &op_nop, &am_imp },{ "ADC", 4, &op_adc, &am_abs_x },{ "ROR", 7, &op_ror, &am_abs_x },{ "xxx", 7, &op_xxx, &am_imp },
    { "xxx", 2, &op_nop, &am_imp },{ "STA", 6, &op_sta, &am_x_ind },{ "xxx", 2, &op_nop, &am_imp },{ "xxx", 6, &op_xxx, &am_imp },{ "STY", 3, &op_sty, &am_zpg },{ "STA", 3, &op_sta, &am_zpg },{ "STX", 3, &op_stx, &am_zpg },{ "xxx", 3, &op_xxx, &am_imp },{ "DEY", 2, &op_dey, &am_imp },{ "xxx", 2, &op_nop, &am_imp },{ "TXA", 2, &op_txa, &am_imp },{ "xxx", 2, &op_xxx, &am_imp },{ "STY", 4, &op_sty, &am_abs },{ "STA", 4, &op_sta, &am_abs },{ "STX", 4, &op_stx, &am_abs },{ "xxx", 4, &op_xxx, &am_imp },
    { "BCC", 2, &op_bcc, &am_rel },{ "STA", 6, &op_sta, &am_ind_y },{ "xxx", 2, &op_xxx, &am_imp },{ "xxx", 6, &op_xxx, &am_imp },{ "STY", 4, &op_sty, &am_zpg_x },{ "STA", 4, &op_sta, &am_zpg_x },{ "STX", 4, &op_stx, &am_zpg_y },{ "xxx", 4, &op_xxx, &am_imp },{ "TYA", 2, &op_tya, &am_imp },{ "STA", 5, &op_sta, &am_abs_y },{ "TXS", 2, &op_txs, &am_imp },{ "xxx", 5, &op_xxx, &am_imp },{ "xxx", 5, &op_nop, &am_imp },{ "STA", 5, &op_sta, &am_abs_x },{ "xxx", 5, &op_xxx, &am_imp },{ "xxx", 5, &op_xxx, &am_imp },
    { "LDY", 2, &op_ldy, &am_imm },{ "LDA", 6, &op_lda, &am_x_ind },{ "LDX", 2, &op_ldx, &am_imm },{ "xxx", 6, &op_xxx, &am_imp },{ "LDY", 3, &op_ldy, &am_zpg },{ "LDA", 3, &op_lda, &am_zpg },{ "LDX", 3, &op_ldx, &am_zpg },{ "xxx", 3, &op_xxx, &am_imp },{ "TAY", 2, &op_tay, &am_imp },{ "LDA", 2, &op_lda, &am_imm },{ "TAX", 2, &op_tax, &am_imp },{ "xxx", 2, &op_xxx, &am_imp },{ "LDY", 4, &op_ldy, &am_abs },{ "LDA", 4, &op_lda, &am_abs },{ "LDX", 4, &op_ldx, &am_abs },{ "xxx", 4, &op_xxx, &am_imp },
    { "BCS", 2, &op_bcs, &am_rel },{ "LDA", 5, &op_lda, &am_ind_y },{ "xxx", 2, &op_xxx, &am_imp },{ "xxx", 5, &op_xxx, &am_imp },{ "LDY", 4, &op_ldy, &am_zpg_x },{ "LDA", 4, &op_lda, &am_zpg_x },{ "LDX", 4, &op_ldx, &am_zpg_y },{ "xxx", 4, &op_xxx, &am_imp },{ "CLV", 2, &op_clv, &am_imp },{ "LDA", 4, &op_lda, &am_abs_y },{ "TSX", 2, &op_tsx, &am_imp },{ "xxx", 4, &op_xxx, &am_imp },{ "LDY", 4, &op_ldy, &am_abs_x },{ "LDA", 4, &op_lda, &am_abs_x },{ "LDX", 4, &op_ldx, &am_abs_y },{ "xxx", 4, &op_xxx, &am_imp },
    { "CPY", 2, &op_cpy, &am_imm },{ "CMP", 6, &op_cmp, &am_x_ind },{ "xxx", 2, &op_nop, &am_imp },{ "xxx", 8, &op_xxx, &am_imp },{ "CPY", 3, &op_cpy, &am_zpg },{ "CMP", 3, &op_cmp, &am_zpg },{ "DEC", 5, &op_dec, &am_zpg },{ "xxx", 5, &op_xxx, &am_imp },{ "INY", 2, &op_iny, &am_imp },{ "CMP", 2, &op_cmp, &am_imm },{ "DEX", 2, &op_dex, &am_imp },{ "xxx", 2, &op_xxx, &am_imp },{ "CPY", 4, &op_cpy, &am_abs },{ "CMP", 4, &op_cmp, &am_abs },{ "DEC", 6, &op_dec, &am_abs },{ "xxx", 6, &op_xxx, &am_imp },
    { "BNE", 2, &op_bne, &am_rel },{ "CMP", 5, &op_cmp, &am_ind_y },{ "xxx", 2, &op_xxx, &am_imp },{ "xxx", 8, &op_xxx, &am_imp },{ "xxx", 4, &op_nop, &am_imp },{ "CMP", 4, &op_cmp, &am_zpg_x },{ "DEC", 6, &op_dec, &am_zpg_x },{ "xxx", 6, &op_xxx, &am_imp },{ "CLD", 2, &op_cld, &am_imp },{ "CMP", 4, &op_cmp, &am_abs_y },{ "NOP", 2, &op_nop, &am_imp },{ "xxx", 7, &op_xxx, &am_imp },{ "xxx", 4, &op_nop, &am_imp },{ "CMP", 4, &op_cmp, &am_abs_x },{ "DEC", 7, &op_dec, &am_abs_x },{ "xxx", 7, &op_xxx, &am_imp },
    { "CPX", 2, &op_cpx, &am_imm },{ "SBC", 6, &op_sbc, &am_x_ind },{ "xxx", 2, &op_nop, &am_imp },{ "xxx", 8, &op_xxx, &am_imp },{ "CPX", 3, &op_cpx, &am_zpg },{ "SBC", 3, &op_sbc, &am_zpg },{ "INC", 5, &op_inc, &am_zpg },{ "xxx", 5, &op_xxx, &am_imp },{ "INX", 2, &op_inx, &am_imp },{ "SBC", 2, &op_sbc, &am_imm },{ "NOP", 2, &op_nop, &am_imp },{ "xxx", 2, &op_sbc, &am_imp },{ "CPX", 4, &op_cpx, &am_abs },{ "SBC", 4, &op_sbc, &am_abs },{ "INC", 6, &op_inc, &am_abs },{ "xxx", 6, &op_xxx, &am_imp },
    { "BEQ", 2, &op_beq, &am_rel },{ "SBC", 5, &op_sbc, &am_ind_y },{ "xxx", 2, &op_xxx, &am_imp },{ "xxx", 8, &op_xxx, &am_imp },{ "xxx", 4, &op_nop, &am_imp },{ "SBC", 4, &op_sbc, &am_zpg_x },{ "INC", 6, &op_inc, &am_zpg_x },{ "xxx", 6, &op_xxx, &am_imp },{ "SED", 2, &op_sed, &am_imp },{ "SBC", 4, &op_sbc, &am_abs_y },{ "NOP", 2, &op_nop, &am_imp },{ "xxx", 7, &op_xxx, &am_imp },{ "xxx", 4, &op_nop, &am_imp },{ "SBC", 4, &op_sbc, &am_abs_x },{ "INC", 7, &op_inc, &am_abs_x },{ "xxx", 7, &op_xxx, &am_imp }
};

